### ISSUE TITLE
[Sandbox] LoxiLB

### ISSUE THREAD

**Issue by nik-netlox** [cncf/sandbox#9]
### Application contact emails

dipj@netlox.io, seokhwan.kong@netlox.io, [nikhil.malik@netlox.io](mailto:nikhil.malik@netlox.io), jaehong.rim@netlox.io

### Project Summary

eBPF based cloud-native external load-balancer for 5G/6G/MEC

### Project Description

loxilb is an open source cloud-native load-balancer based on GoLang/eBPF with the goal of achieving cross-compatibility across a wide range of on-prem, public-cloud or hybrid K8s environments. loxilb is being developed to support the adoption of cloud-native tech in telco, mobility, and edge computing.

Kubernetes defines many service constructs like cluster-ip, node-port, load-balancer, ingress etc for pod to pod, pod to service and outside-world to service communication.    

![Image](https://github.com/user-attachments/assets/3d9646b4-9d2e-43d7-a673-d26b49352d3a)

All these services are provided by load-balancers/proxies operating at Layer4/Layer7. Since Kubernetes's is highly modular, these services can be provided by different software modules. For example, kube-proxy is used by default to provide cluster-ip and node-port services. For some services like LB and Ingress, no default is usually provided.

Service type load-balancer is usually provided by public cloud-provider(s) as a managed entity. But for on-prem and self-managed clusters, there are only a few good options available. Even for provider-managed K8s like EKS, there are many who would want to bring their own LB to clusters running anywhere. Additionally, Telco 5G and edge services introduce unique challenges due to the variety of exotic protocols involved, including GTP, SCTP, SRv6, and DTLS, making seamless integration particularly challenging. loxilb provides service type load-balancer as its main use-case. loxilb can be run in-cluster or ext-to-cluster as per user need.

loxilb works as a L4 load-balancer/service-proxy by default. Although L4 load-balancing provides great performance and functionality, an equally performant L7 load-balancer is also necessary in K8s for various use-cases. loxilb also supports L7 load-balancing in the form of Kubernetes Ingress implementation which is enhanced with eBPF sockmap helpers. This also benefit users who need L4 and L7 load-balancing under the same hood.

Additionally, loxilb also supports:   
- [x] kube-proxy replacement with eBPF(full cluster-mesh implementation for Kubernetes)   
- [x] Ingress Support   
- [x] Kubernetes Gateway API   

### Org repo URL

https://github.com/loxilb-io/

### Project repo URL

https://github.com/loxilb-io/loxilb

### Additional repos

https://github.com/loxilb-io/loxilb-ebpf
https://github.com/loxilb-io/loxilbdocs
https://github.com/loxilb-io/loxi-ccm
https://github.com/loxilb-io/loxicmd
https://github.com/loxilb-io/kube-loxilb
https://github.com/loxilb-io/loxilb-ingress

### Website URL

https://www.loxilb.io/

### Roadmap

https://github.com/loxilb-io/loxilbdocs/blob/main/docs/roadmap.md

### Contributing Guide

https://github.com/loxilb-io/loxilb/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/loxilb-io/loxilb/blob/main/CODE_OF_CONDUCT.md

### Adopters

[ADOPTERS.md](https://github.com/loxilb-io/loxilb/blob/main/ADOPTERS.md)

### Contributing or Sponsoring Org

https://www.netlox.io/

### Maintainers file

https://github.com/loxilb-io/loxilb/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

LoxiLB was designed to be cloud-native load-balancer, enabling Linux's eBPF technology to be used as its core engine. We have brought LoxiLB to a state where it can show its true potential. We are seeking visibility, community adoption and contributors to take it to the next level. The CNCF can provide the necessary guidance, platform, visibility, and support for LoxiLB.

### Benefit to the Landscape

LoxiLB is trying to fill the gap in the Edge Computing. Edge services are a different ball game altogether since there are so many exotic protocols in play like GTP, SCTP, SRv6 etc and integrating everything into a seamlessly working solution has been quite difficult. LoxiLB provides load balancer services for all these protocols, and it was made easy with eBPF technology by Linux.
During the journey of LoxiLB's development, we developed many other generic networking/security/visibility features in it using eBPF which can be used for various other purposes not specific to load-balancer only. But we decided to stick our original name LoxiLB as load-balancing will continue to be its main purpose in the foreseeable future. LoxiLB team hopes the open-source community finds it helpful.

### Cloud Native 'Fit'

LoxiLB offers service as cloud-native load-balancer in Kubernetes environment. LoxiLB turns Kubernetes network load balancing into high speed, flexible and programmable LB services. It automates the tasks of external load balancer administration: deployment, bootstrapping, configuration, provisioning, scaling, upgrading, migration, routing, monitoring, and resource management.

### Cloud Native 'Integration'

- Kubernetes: Offers service as external load-balancer
- docker: LoxiLB can be deployed as a docker container
- Works with any Kubernetes distribution/CNI - k8s/k3s/k0s/kind/OpenShift + Calico/Flannel/Cilium/Multus etc

### Cloud Native Overlap

LoxiLB does have some overlapping functionality with MetalLB and Openelb project as they are also external load-balancers.

### Similar projects

Similar project to LoxiLB would be MetalLB and Openelb. Few differentiating factors are: 
* LoxiLB offers Load balancer services using eBPF technology.
* Tailored for Telco-oriented 5G/6G/MEC specific use-cases  e.g., [Service Communication Proxy](https://dev.to/nikhilmalik/5g-service-communication-proxy-with-loxilb-4242), GTP, SRv6, SCTP, Multi-Homing etc. 
* Supports both external and in-cluster mode.
* Offers Disaster Recovery across Multi-AZ/Multi-Region/Multi-cloud/OnPrem.

### Product or Service to Project separation

Netlox is into cloud-native consulting, education and  solutions. LoxiLB was started as a side-project to fill in the gaps we found while building cloud-native solutions with the user community. LoxiLB's roadmap is essentially driven by the community feedback and requirements. That will remain to be so in the foreseeable future. Netlox uses unmodified open-source LoxiLB as it is in some of its solutions and also commercially supports anyone who needs SLA backed support.

### Project presentations
[Presented to CNCF TAG-Network](https://docs.google.com/presentation/d/1hEyQR7g8OtLysnm4XQ7Up36M60ERPyjdYTbmW9VGVt8/edit#slide=id.g275aefc6786_1_5)
[NAVER CLOUD MASTER DAY 2024 (SAMSUNG)](https://blog.naver.com/n_cloudplatform/223518118906)
[eBPF Summit 2023](https://www.youtube.com/watch?v=RiyBc-mvG_k)
[OpenInfra & Cloud Native Days Korea 2022](https://www.youtube.com/watch?v=MleGRc7Rzu4)
[APNOMS JAPAN 2022](https://www.ieice.org/~icm/apnoms/2022/specialSessions.html)

### Project champions

N/A

### Additional information

N/A

**Comment by dims** [comment]
@nik-netlox is https://github.com/loxilb-io/loxilb-ebpf missed out on purpose or an oversight?

**Comment by nik-netlox** [comment]
@dims , it was an oversight. I am adding it in the additional repos.

**Comment by nik-netlox** [comment]
We have recently released kube-loxilb (loxilb's implementation of kubernetes service load-balancer spec). I have updated the same in additional repos as well.

**Comment by nik-netlox** [comment]
Thank you for reviewing our application and recommendations. LoxiLB has 7 dedicated developers and is constantly growing in popularity and contributions from other users. Recently, it crossed 500+ stars on the github. We are taking every step possible to extend it's reach. We will reach out to TAG contributor strategy and re-apply after sometime.

**Comment by amye** [comment]
Checking in, it's been a little over a year in here. 
Still interested?

**Comment by nik-netlox** [comment]
Hi @amye,
Yes, we are interested in re-applying. Should I re-open this issue or create a new one?

**Comment by amye** [comment]
Let's reopen this one and add more details in here.

**Comment by nik-netlox** [comment]
Thanks for reconsidering our application. As suggested in the last ToC meeting, we reached out to TAG Contributor strategy and discussed. And, as per their feedback we have incorporated a few changes including adding Maintainer's policy.

To summarize the loxilb project growth since last meeting:
- Adoptions from multiple organizations.
- Contributors from different organizations and a few independent contributors as well(including [user blogs](https://loxilb-io.github.io/loxilbdocs/#community-posts)).
- Increased user base.

 In terms of metrics:

| Metric | Previous | Current |
|---|---|---|
|Stars|500+|1.3k+|
|Contributors|7|12|
|Package Download|20k+|90k+|
|Forks|20+|73|
|No. of Commits|1200+|2400+|

**Comment by dims** [comment]
Is there some feedback from `TAG Network` folks? @leecalcote perhaps?

**Comment by TheFoxAtWork** [comment]
Once we hear from TAG Network, we will add to the Upcoming column for the next Sandbox meeting (today's got a full agenda)

**Comment by nik-netlox** [comment]
We presented LoxiLB in the TAG Network Meeting held on 25th April 2024. Thanks @nicholasjackson for providing us the opportunity to present and discuss its use-cases. Please find the presented ppt with demo video [here](https://docs.google.com/presentation/d/1hEyQR7g8OtLysnm4XQ7Up36M60ERPyjdYTbmW9VGVt8/edit?usp=drive_link).

**Comment by nicholasjackson** [comment]
@TheFoxAtWork Hi Emily, @nik-netlox presented their project to us during the bi-weekly meeting, we also chatted Friday last week. TAG Network is very happy to back LoxiLB's nomination for Sanbox, we feel that LoxiLB is widely useful to all Cloud Native users, it is specifically addresses many use cases and requirements specific to the telecommunications industry. 

I apologise but I could not find if there are any minimum metrics on contributors for inclusion, Loxi have been expanding their contributor diversity and are continuing to grow this. Inclusion as a sandbox project would also assist this growth.

Happy to chat about any of these and support the application during the next TOC sandbox meeting.

Kind regards,

Nic

**Comment by TheFoxAtWork** [comment]
thanks @nicholasjackson !!  CC @jeefy for updating the sandbox queue.

**Comment by TheFoxAtWork** [comment]
@mrbobbytables @jeefy This project needs moved to the top of the upcoming queue for our next sandbox mtg.  It appears we missed moving this over.

**Comment by linsun** [comment]
Hi @nik-netlox - The project looks solid!  Since the review with TAG network on April 25 2024, I'm curious how the contributions have been outside the main company Netlox, which all of the [maintainers](https://github.com/loxilb-io/loxilb/blob/main/MAINTAINERS.md) are from.

**Comment by nik-netlox** [comment]
Thank you @linsun, 
Including all the repos, We have 7 contributors from our organization and more than 10 contributors from outside our organization. Also, we are compiling a list of adoptors/users and add it in our github soon.

I will summarize our project's growth since the TAG Network meeting with the stats from the main repo:

| Metric | Mar 2023 | Apr 2024 | Jul 2024|
|---|---|---|---|
|Stars|500+|1.3k+|1.4k+|
|Total Contributors|7|12|16|
|Package Download|20k+|90k+|131k+|
|Forks|20+|73|86|
|No. of Commits|1200+|2400+|2800+|

Additionally, 
- Samsung Electronics [presented a solution](https://blog.naver.com/n_cloudplatform/223518118906) for 5G with LoxiLB in an event called NAVER CLOUD MASTER DAY 2024.(The language is Korean, please use google translate for English).
- Researchers from a University in EU chose LoxiLB and published [a Research Paper](https://arxiv.org/pdf/2405.00078).

**Comment by nik-netlox** [comment]
[LoxiLB's Adopters list](https://github.com/loxilb-io/loxilb/blob/main/ADOPTERS.md) has been added in the github.

**Comment by nik-netlox** [comment]
@xmulligan , Thank you for reviewing our application but to clarify regarding external contributors in the past year, we had 9 external contributors. Please refer to the [github stats](https://github.com/loxilb-io/loxilb/graphs/contributors?from=2023-07-01&to=2024-08-04&type=c) from the main repo.

**Comment by xmulligan** [comment]
Sorry my mistake, I was looking at the docs repo instead by accident. I've updated the comment above now.

**Comment by jberkus** [comment]
You declined to answer "Product or Service to Project separation".  Given that you are a small company, and LoxiLB appears to be related to all of your company's products, you need to fill out that section.  Thanks.

**Comment by nik-netlox** [comment]
Thanks @jberkus for pointing it out. I have updated the application.

> Netlox is into cloud-native consulting, education and solutions. LoxiLB was started as a side-project to fill in the gaps we found while building cloud-native solutions with the user community. LoxiLB's roadmap is essentially driven by the community feedback and requirements. That will remain to be so in the foreseeable future. Netlox uses unmodified open-source LoxiLB as it is in some of its solutions and also commercially supports anyone who needs SLA backed support.

**Comment by jberkus** [comment]
Thanks, that looks good.

**Comment by nsko** [comment]
I am from ETRI in South Korea. Our consortium consists of {ETRI, SK Telecom, LGU+, etc}.  We are co-working with loxilb team for the Korea Gov R&D project(Evolved SBA Framework for 5G/6G Mobile Core). We are planning to provide guidance in cloud-native telco area and also act as Maintainer pending internal approval.

**Comment by seokho-son** [comment]
Hello! I am a CNCF Ambassador based in South Korea. 
I'm excited to see that the useful open-source project Loxilb is up for a vote to enter the CNCF Sandbox. 
The Loxilb contributors have been actively sharing valuable networking technologies and information, especially within the Korean Kubernetes User Group. I am hopeful for a positive outcome! My sign of support: 👍

**Comment by Cmierly** [comment]
Welcome and congrats on getting accepted as a CNCF Sandbox project!

You can get started on your on-boarding checklist here: https://github.com/cncf/toc/issues/1409

and if you have any questions, please don't hesitate to reach out!

**Comment by mrbobbytables** [comment]
With https://github.com/cncf/toc/issues/1409 created, we can go ahead and close this out :)

Congrats again!
